<td class="calendar-time-col" style="width: 96px;">
    <?=
    $this->calendarTimeTable($this->squareTimings) ?>
</td>

<?php

$reservations = $this->get('reservations');
$events = $this->get('events');
        //         echo '<pre>';
        // var_dump($timeBlockCount);
        // echo '</pre>';
        // die();
$reservationsForColPlugin = $this->plugin('CalendarReservationsForCol');
$reservationsCleanupPlugin = $this->plugin('CalendarReservationsCleanup');

$eventsForColPlugin = $this->plugin('CalendarEventsForCol');
$eventsCleanupPlugin = $this->plugin('CalendarEventsCleanup');

/* Loop through day cols */

$walkingDate = clone $this->dateStart;
$walkingIndex = 0;

while ($walkingDate <= $this->dateEnd) {
    if (in_array($walkingDate->format($this->t('Y-m-d')), $this->dayExceptions) ||
        in_array($this->t($walkingDate->format('l')), $this->dayExceptions)) {

        if (! in_array($walkingDate->format($this->t('Y-m-d')), $this->dayExceptionsExceptions)) {
            $walkingDate->modify('+1 day');
            $walkingIndex++;
            continue;
        }
    }

    echo sprintf('<td class="calendar-date-col %s">',
        ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 5 - $walkingIndex)) : ''));

    echo '<table class="calendar-date-table full-width">';

    echo $this->calendarDateRow($walkingDate, $this->squaresCount);
    echo $this->calendarSquareRow($this->squares, $this->squaresCount);

    /* Loop through time rows */
        // echo '<pre>';
        // var_dump($this->squareTimings);
        // echo '</pre>';
        // die();
    foreach ($this->squareTimings as $timing) {
        echo '<tr class="calendar-core-row">';

        $walkingDate->modify('+' . $timing['timeStart'] . ' sec');

        $reservationsForCol = $reservationsForColPlugin($reservations, $walkingDate, $timing['timeStart'], $timing['timeBlock']);
        $eventsForCol = $eventsForColPlugin($events, $walkingDate, $timing['timeStart'], $timing['timeBlock']);


        foreach ($this->squares as $square) {
            echo $this->calendarCellLogic($walkingDate, $timing['timeStart'], $timing['timeBlock'], $this->dateNow,
                $square, $this->user, $reservationsForCol, $eventsForCol,$timing['square']);
        }

        $walkingDate->setTime(0, 0, 0);

        echo '</tr>';
    }

    $reservationsCleanupPlugin($reservations, $walkingDate);
    $eventsCleanupPlugin($events, $walkingDate);

    echo $this->calendarSquareRow($this->squares, $this->squaresCount, 'no-print');
    echo $this->calendarDateRow($walkingDate, $this->squaresCount, 'no-print');

    echo '</table>';

    echo '</td>';

    $walkingDate->modify('+1 day');
    $walkingIndex++;
}
